functionsDirectory = "/Users/alanphillips/Downloads/shibmetrics/netlify/functions"
functionsDirectoryOrigin = "config"
headersOrigin = "config"
redirectsOrigin = "config"

[build]
publish = "/Users/alanphillips/Downloads/shibmetrics/.next"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "/Users/alanphillips/Downloads/shibmetrics/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[template]

[template.environment]
NEXT_PUBLIC_ETHERSCAN_API_KEY = "Your Etherscan API key here"

[functions]

[functions."*"]
included_files = ["lib/**", "app/api/**"]

[[plugins]]
origin = "default"
package = "@netlify/plugin-nextjs"
pinned_version = "5"

[plugins.inputs]

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
for = "/api/*"

[headers.values]
Cache-Control = "public, max-age=300, s-maxage=300"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]