functionsDirectory = "/Users/alanphillips/Downloads/shibmetrics/netlify/functions"
functionsDirectoryOrigin = "config"
headersOrigin = "inline"
redirectsOrigin = "inline"

[build]
publish = "/Users/alanphillips/Downloads/shibmetrics/.next"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "/Users/alanphillips/Downloads/shibmetrics/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[template]

[template.environment]
NEXT_PUBLIC_ETHERSCAN_API_KEY = "Your Etherscan API key here"

[functions]

[functions."*"]
included_files = ["lib/**", "app/api/**", ".env", ".env.production", ".env.local", ".env.production.local"]

[[plugins]]
origin = "default"
package = "@netlify/plugin-nextjs"
pinned_version = "5"

[plugins.inputs]

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
for = "/api/*"

[headers.values]
Cache-Control = "public, max-age=300, s-maxage=300"

[[headers]]
for = "/_next/static/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/_next/image"
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200.0
force = false

[redirects.query]
url = ":url"
w = ":width"
q = ":quality"

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/_ipx/*"
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200.0
force = false

[redirects.query]
url = ":url"
w = ":width"
q = ":quality"

[redirects.conditions]

[redirects.headers]