[build]
  publish = ".next"
  command = "npm run build"

[functions]
  directory = "netlify/functions"
  included_files = ["lib/**", "app/api/**"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[template.environment]
  NEXT_PUBLIC_ETHERSCAN_API_KEY = "Your Etherscan API key here"

# Next.js API routes are automatically handled by Netlify
# Remove manual redirects that might interfere

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "public, max-age=300, s-maxage=300" 